# Generated by Django 3.0.3 on 2020-03-05 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('splitbackend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='name',
            field=models.CharField(default='Food', max_length=30),
            preserve_default=False,
        ),
    ]
