# Generated by Django 3.0.3 on 2020-03-05 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('splitbackend', '0003_tab_owner_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='tab_id',
            new_name='tab',
        ),
        migrations.RenameField(
            model_name='split',
            old_name='item_id',
            new_name='item',
        ),
        migrations.RenameField(
            model_name='split',
            old_name='profile_id',
            new_name='profile',
        ),
        migrations.RenameField(
            model_name='tab',
            old_name='owner_id',
            new_name='owner',
        ),
    ]
