# Generated by Django 3.0.3 on 2020-03-05 19:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('splitbackend', '0004_auto_20200305_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tab',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to='splitbackend.Profile'),
        ),
    ]
