# Generated by Django 3.0.3 on 2020-03-05 22:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('splitbackend', '0006_auto_20200305_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='tab',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='splitbackend.Tab'),
        ),
        migrations.AlterField(
            model_name='split',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='splits', to='splitbackend.Item'),
        ),
        migrations.AlterField(
            model_name='split',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participated_splits', to='splitbackend.Profile'),
        ),
        migrations.AlterField(
            model_name='tab',
            name='participants',
            field=models.ManyToManyField(related_name='tabs', to='splitbackend.Profile'),
        ),
    ]
