# Generated by Django 3.0.3 on 2020-03-08 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('splitbackend', '0008_auto_20200306_1656'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='update_at',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='update_at',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='split',
            old_name='update_at',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='tab',
            old_name='update_at',
            new_name='updated_at',
        ),
        migrations.AlterField(
            model_name='split',
            name='percent',
            field=models.DecimalField(decimal_places=3, default=1, max_digits=4),
        ),
    ]
