# Generated by Django 3.0.3 on 2020-03-08 23:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('splitbackend', '0009_auto_20200308_1926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='cost',
            field=models.DecimalField(decimal_places=2, max_digits=17, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(3)]),
        ),
        migrations.AlterField(
            model_name='split',
            name='percent',
            field=models.DecimalField(decimal_places=3, default=1, max_digits=4, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='tab',
            name='title',
            field=models.CharField(default='Outing', max_length=30, validators=[django.core.validators.MinLengthValidator(3)]),
        ),
    ]
