# Generated by Django 3.0.3 on 2020-03-12 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('splitbackend', '0012_auto_20200311_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tab',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='tabs', to='splitbackend.Profile'),
        ),
    ]
